version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "twitter-auto-delete"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1tlmrs0hhorm1"
s3_prefix = "twitter-auto-delete"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
