AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  twitter-auto-delete
  
Globals:
  Function:
    Timeout: 60

Resources:
  TwitterAutoDeleteFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: twitter-auto-delete/
      Handler: app.handler
      Runtime: nodejs12.x
      Environment: 
        Variables:
          CONSUMER_KEY: !Ref ConsumerKey
          CONSUMER_SECRET: !Ref ConsumerSecret
          ACCESS_TOKEN: !Ref AccessToken
          ACCESS_TOKEN_SECRET: !Ref AccessTokenSecret
          TWITTER_USERNAME: !Ref TwitterUsername
          DAYS_OLD_DELETE: !Ref DaysOldDelete
          ARCHIVE_BUCKET: !Ref ArchiveBucket
      Events:
        TwitterAutoDelete:
          Type: Schedule
          Properties:
            Schedule: rate(1 day)
            Name: daily-delete
            Description: daily-delete
            Enabled: True
      Policies:
        - AWSLambdaExecute
        - Version: '2012-10-17' 
          Statement:
            - Effect: Allow
              Action:
                - s3:*Object
              Resource: !GetAtt S3TweetArchiveBucket.Arn
  S3TweetArchiveBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref ArchiveBucket

        
Parameters:
  ConsumerKey:
    Type: String
  ConsumerSecret:
    Type: String
  AccessToken:
    Type: String
  AccessTokenSecret:
    Type: String
  TwitterUsername:
    Type: String
  DaysOldDelete:
    Type: Number
  ArchiveBucket:
    Type: String
    Default: 'deleted-tweets-archive'


Outputs:
  TwitterAutoDeleteFunction:
    Description: "Lambda Function ARN"
    Value: !GetAtt TwitterAutoDeleteFunction.Arn
  TwitterAutoDeleteFunctionIamRole:
    Description: "Implicit IAM Role created for function"
    Value: !GetAtt TwitterAutoDeleteFunctionRole.Arn
